= Table.RenameColumns(#"Removed Other Columns",{{"CatchWeightUnitSymbol", "sdfsda"}, {"ProductStyleId", "#Dim-04"}, {"ProductConfigurationId", "#Dim-01"}, {"ProductSizeId", "#Dim-02"}, {"ProductVersionId", "#Dim-05"}, {"ProductColorId", "#Dim-03"}, {"RetailProductVariantNumber", "VariantNumber"}, {"ProcurementProductCategoryName", "Procurement-Category"}, {"ProjectId", "Site-ID"}})
