= Table.ReorderColumns(#"Renamed Columns",{"PurchaseOrderNumber", "LineNumber", "LineDescription", "OrderedPurchaseQuantity", "PurchaseUnitSymbol", "PurchasePrice", "LineAmount", "VariantNumber", "#Dim-01", "#Dim-02", "#Dim-03", "#Dim-04", "#Dim-05", "Procurement-Category", "PurchaseOrderLineStatus", "Site-ID", "FormattedDelveryAddress", "LineDiscountAmount", "ProjectTaxGroupCode", "ProjectTaxItemGroupCode", "RequestedDeliveryDate", "ReceivingWarehouseId", "RequesterPersonnelNumber", "ProjectLinePropertyId", "FixedPriceCharges", "PurchasePriceQuantity", "DeliveryAddressName", "FixedAssetTransactionType", "IsDeliveryAddressPrivate", "sdfsda", "ProjectSalesCurrencyCode", "DeliveryAddressLocationId", "ProjectActivityNumber", "SalesTaxItemGroupCode", "DeliveryAddressStreet", "CustomerReference", "SalesTaxGroupCode", "LineDiscountPercentage", "AllowedUnderdeliveryPercentage", "AllowedOverdeliveryPercentage", "DefaultLedgerDimensionDisplayValue", "VendorInvoiceMatchingPolicy", "ProjectSalesPrice", "IsLineStopped", "ProjectCategoryId", "ProjectSalesUnitSymbol", "ReceivingSiteId"})
