let
    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1VEVnAPBxqgFEVAfglRwMAuWO1Qx7buKT9NEVyoz1hS8/edit?gid=0#gid=0"),
    Sheet1_Table = Source{[name="Sheet1",ItemKind="Table"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Table, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Line", Int64.Type}, {"Requester", type text}, {"Buying legal entity", type text}, {"Receiving operating unit", type text}, {"Item number", type text}, {"Variant number", type text}, {"Procurement category", type text}, {"Product name", type text}, {"Quantity", type number}, {"Unit", type text}, {"Unit price", type number}, {"Net amount", type number}, {"Currency", type text}, {"Vendor account", type any}, {"Vendor name", type any}, {"Status", type text}, {"Purchase requisition reference", Int64.Type}, {"Dimension 1", type text}, {"Dimension 2", type any}, {"Dimension 3", type any}, {"Dimension 4", type text}, {"Dimension 5", type text}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Purchase requisition reference"}, PurchaseRequisisionHeaders, {"Purchase requisition"}, "PurchaseRequisisionHeaders", JoinKind.Inner),
    #"Expanded PurchaseRequisisionHeaders1" = Table.ExpandTableColumn(#"Merged Queries", "PurchaseRequisisionHeaders", {"Name", "Submitted date"}, {"PurchaseRequisisionHeaders.Name", "PurchaseRequisisionHeaders.Submitted date"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expanded PurchaseRequisisionHeaders1",{"PurchaseRequisisionHeaders.Name", "Line", "Requester", "Buying legal entity", "Receiving operating unit", "Item number", "Variant number", "Procurement category", "Product name", "Quantity", "Unit", "Unit price", "Net amount", "Currency", "Vendor account", "Vendor name", "Status", "Purchase requisition reference", "Dimension 1", "Dimension 2", "Dimension 3", "Dimension 4", "Dimension 5"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Line", "Requester", "Buying legal entity", "Receiving operating unit", "Unit price", "Net amount", "Currency", "Vendor account", "Vendor name"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns",{"Purchase requisition reference", "PurchaseRequisisionHeaders.Name", "PurchaseRequisisionHeaders.Submitted date", "Item number", "Variant number", "Procurement category", "Product name", "Quantity", "Unit", "Status", "Dimension 1", "Dimension 2", "Dimension 3", "Dimension 4", "Dimension 5"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns1",{{"Purchase requisition reference", "PurchaseRequisisionNumber"}, {"PurchaseRequisisionHeaders.Name", "PurchaseRequisisionName"}, {"PurchaseRequisisionHeaders.Submitted date", "Date"}, {"Dimension 1", "#Dim_1"}, {"Dimension 2", "#Dim_2"}, {"Dimension 3", "#Dim_3"}, {"Dimension 4", "#Dim_4"}, {"Dimension 5", "#Dim_5"}})
in
    #"Renamed Columns"
