let
    Source = OData.Feed("https://edecs.operations.eu.dynamics.com/data", null, [Implementation="2.0"]),
    PurchaseOrderLines_table = Source{[Name="PurchaseOrderLinesV2",Signature="table"]}[Data],
    #"Removed Other Columns" = Table.SelectColumns(PurchaseOrderLines_table,{"PurchaseOrderNumber", "LineNumber", "ProcurementProductCategoryName", "ProjectSalesUnitSymbol", "OrderedPurchaseQuantity", "FormattedDelveryAddress", "ProjectCategoryId", "RetailProductVariantNumber", "ItemNumber" , "LineDiscountAmount", "ProductStyleId", "ProjectTaxGroupCode", "ProjectTaxItemGroupCode", "ProductConfigurationId", "RequestedDeliveryDate", "ReceivingWarehouseId", "PurchaseUnitSymbol", "RequesterPersonnelNumber","PurchaseRequisitionId", "ProjectId", "ProjectLinePropertyId", "ProductSizeId", "FixedPriceCharges", "PurchasePriceQuantity", "DeliveryAddressName", "FixedAssetTransactionType", "IsDeliveryAddressPrivate","ReceivingSiteId", "ProjectSalesCurrencyCode", "DeliveryAddressLocationId", "ProjectActivityNumber", "SalesTaxItemGroupCode", "ProductVersionId", "LineDescription", "DeliveryAddressStreet", "CustomerReference", "SalesTaxGroupCode", "PurchasePrice", "LineDiscountPercentage", "AllowedUnderdeliveryPercentage", "AllowedOverdeliveryPercentage", "PurchaseOrderLineStatus", "DefaultLedgerDimensionDisplayValue", "ProductColorId", "LineAmount", "VendorInvoiceMatchingPolicy", "ProjectSalesPrice", "IsLineStopped"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([ReceivingSiteId] = ProjectID)),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"ProductStyleId", "#Dim-04"}, {"ProductConfigurationId", "#Dim-01"}, {"ProductSizeId", "#Dim-02"}, {"ProductVersionId", "#Dim-05"}, {"ProductColorId", "#Dim-03"}, {"RetailProductVariantNumber", "VariantNumber"}, {"ProcurementProductCategoryName", "Procurement-Category"}, {"ProjectId", "Site-ID"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"PurchaseOrderNumber", "LineNumber", "LineDescription", "ItemNumber", "VariantNumber", "#Dim-01", "#Dim-02", "#Dim-03", "#Dim-04", "#Dim-05", "Procurement-Category", "ReceivingSiteId", "ReceivingWarehouseId", "RequestedDeliveryDate", "OrderedPurchaseQuantity", "PurchaseUnitSymbol", "PurchasePrice", "LineAmount", "ProjectSalesCurrencyCode", "PurchaseOrderLineStatus", "RequesterPersonnelNumber", "PurchaseRequisitionId", "ProjectTaxGroupCode", "FormattedDelveryAddress", "LineDiscountAmount", "ProjectTaxItemGroupCode", "ProjectLinePropertyId", "SalesTaxItemGroupCode", "SalesTaxGroupCode", "PurchasePriceQuantity", "DeliveryAddressName", "FixedAssetTransactionType", "IsDeliveryAddressPrivate", "DeliveryAddressLocationId", "ProjectActivityNumber", "DeliveryAddressStreet", "CustomerReference", "LineDiscountPercentage", "AllowedUnderdeliveryPercentage", "AllowedOverdeliveryPercentage", "DefaultLedgerDimensionDisplayValue", "VendorInvoiceMatchingPolicy", "ProjectSalesPrice", "IsLineStopped", "ProjectCategoryId", "ProjectSalesUnitSymbol", "FixedPriceCharges", "Site-ID"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"RequestedDeliveryDate", type datetime}}),

    // ðŸ”¹ ÙÙ„ØªØ±Ø© Incremental Refresh
    #"Filtered by Date" = Table.SelectRows(#"Changed Type", each [RequestedDeliveryDate] >= RangeStart and [RequestedDeliveryDate] < RangeEnd),

    #"Lowercased Text" = Table.TransformColumns(#"Filtered by Date",{{"LineDescription", Text.Lower, type text}, {"#Dim-01", Text.Lower, type text}, {"#Dim-02", Text.Lower, type text}, {"#Dim-03", Text.Lower, type text}, {"#Dim-04", Text.Lower, type text}, {"#Dim-05", Text.Lower, type text}})
in
    #"Lowercased Text"
