let
    Source = Excel.Workbook(File.Contents("C:\Users\a.abdelnaser\Downloads\Steel HSR 98 -master - Rev 013-GARB.xlsx"), null, true),
    Summerized_Table_Table = Source{[Item="Summerized_Table",Kind="Table"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Summerized_Table_Table,{{"م", Int64.Type}, {"العنصر", type text}, {"المحور ", type text}, {"رقم الكوبري", type text}, {"العدد الاجمالي Part1", Int64.Type}, {"العدد الاجمالي Part2", Int64.Type}, {"العدد الاجمالي ", Int64.Type}, {"العدد المنفذ", Int64.Type}, {"الوحدة ", type text}, {"D8", Int64.Type}, {"D10", type number}, {"D12", type number}, {"D16", type number}, {"D18", type number}, {"D20", Int64.Type}, {"D22", type number}, {"D25", type number}, {"D32", type number}, {"SPIRAL", Int64.Type}, {"الكمية للعنصر ", type number}, {"الكمية الاجمالية Ton", type number}, {"Invoice No:", type text}, {"موقف الحصر ", type text}, {"No", type number}, {"total", type number}, {"موقف الحصر 2", type number}, {"T 8", Int64.Type}, {"T 10", type number}, {"T 12", type number}, {"T 16", type number}, {"T 18", type number}, {"T 20", Int64.Type}, {"T 22", type number}, {"T 25", type number}, {"T 32", type number}, {"التاريخ ", type any}, {"link IR", type text}, {"IR2", type text}, {"مقاول التنفيذ 2", type text}, {"نسبة الصرف ", type number}, {"العدد المنفذ2", type number}, {"الاجمالي ", type number}, {"COMMENT", type text}}),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"الكمية للعنصر "}),
    #"Removed Columns" = Table.RemoveColumns(#"Removed Errors",{"التاريخ ", "COMMENT"}),
    #"Removed Bottom Rows" = Table.RemoveLastN(#"Removed Columns",1),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Bottom Rows",null,0,Replacer.ReplaceValue,{"العدد الاجمالي Part1", "العدد الاجمالي Part2", "العدد الاجمالي ", "العدد المنفذ"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"طن",Replacer.ReplaceValue,{"الوحدة "}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,"Not Defined",Replacer.ReplaceValue,{"مقاول التنفيذ 2"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Replaced Value2",{"Invoice No:", "موقف الحصر ", "No", "total", "موقف الحصر 2", "T 8", "T 10", "T 12", "T 16", "T 18", "T 20", "T 22", "T 25", "T 32"})
in
    #"Removed Columns1"
